name: "Buzz Test Recipe"
version: "1.0.0"

tasks:
  - action: download_github
    src: https://github.com/Native-Software/eup-ui
    ref: main
    dest: ./resources/eup-ui

  - action: write_file
    path: ./server.cfg
    data: |
      sv_hostname "Buzz Test Server"
      ensure eup-ui
